### ISSUE TITLE
Windows powershell error

### ISSUE THREAD

**Issue by flanderb** [StabbyCutyou/rapp#9]
Windows 7
running in a powershell.
When running rapp $app_name.  no such file or directory

Fixed this by changing line 31 from:
root_dir = "#{'pwd'.strip}/#{app_name}"
To:
root_dir = "#{Dir.pwd.strip}/#{app_name}"

Actual Error:
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rapp-0.3.1/lib/rapp/builder.rb:31:in ``': No such file or directory - pwd (Errno:
:ENOENT)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rapp-0.3.1/lib/rapp/builder.rb:31:in`new_app'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rapp-0.3.1/bin/rapp:8:in `<top (required)>'
        from C:/Ruby22-x64/bin/rapp:23:in`load'
        from C:/Ruby22-x64/bin/rapp:23:in `<main>'

**Comment by StabbyCutyou** [comment]
I really need to work on my email filters, because I never got an alert from this! Sorry for not seeing it sooner.

I hadn't considered windows support for this, so I can take a look at finding a platform agnostic approach. That fix won't work on *nix or OSX I'm afraid, but good that you found a temp workaround for the time being.

**Comment by StabbyCutyou** [comment]
Ah, you're using Dir, the ruby class,  not a back ticked powershell call.

That would fix it. I'll pr it in today.

**Comment by flanderb** [comment]
Thank you Mr.(I'm assuming it is a Mr) StabbyCutyou.  No problem about not seeing the issue sooner.  Thank you for the feedback.

**Comment by StabbyCutyou** [comment]
Haha, It is Mr.

I've got the issue addressed in a PR - if you'd be good enough to verify it fixes your issue, I'll release a new copy of the gem asap.

**Comment by StabbyCutyou** [comment]
I've pinged you on a PR if you want to review

https://github.com/StabbyCutyou/rapp/pull/10

**Comment by StabbyCutyou** [comment]
I've pushed a new gem, 0.3.2, to fix this issue. Let me know if anything else pops up.
